spring.application.name=anpa-api-gateway

# 1. Ruta 1: Servicio de clientes
spring.cloud.gateway.server.webflux.routes[0].id=anpa-customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ANPA-CUSTOMER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/api/v1/customers/**

# 2. Ruta 2: Servicio de productos
spring.cloud.gateway.server.webflux.routes[1].id=anpa-product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ANPA-PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/api/v1/products/**


# 3. Ruta 3: Servicio de facturacion
spring.cloud.gateway.server.webflux.routes[2].id=anpa-shopping-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ANPA-SHOPPING-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates=Path=/api/v1/invoices/**

# Define un ID de instancia unico combinando el nombre de la app y valor aleatorio
eureka.instance-id=${spring.application.name}:${random.value}